#!/bin/bash
#
# Saumon i3blocks scripts
# battery (battery percentage and state)
#

battery=${BLOCK_INSTANCE:-BAT0}

capacity=$(<"/sys/class/power_supply/$battery/capacity")
charging=$(<"/sys/class/power_supply/AC/online")

if [ "$charging" -eq 1 ]; then
  color="#8BC34A"
elif [ "$capacity" -lt 50 ]; then
  color="#ff9800"
elif [ "$capacity" -lt 25 ]; then
  color="#f44336"
else
  color="#cccccc"
fi

icon=""  # full
if [ "$capacity" -lt 95 ]; then
  icon=""  # almost full
elif [ "$capacity" -lt 50 ]; then
  icon=""  # half-full
elif [ "$capacity" -lt 25 ]; then
  icon=""  # almost empty
fi

printf "<span color='%s'> %s  %s<span font_size='small'>%% </span></span>\n" "$color" "$icon" "$capacity"
