#!/usr/bin/env bash
#
# Saumon i3blocks scripts
# capslock (caps lock indicator)
#

caps_status=$(xset -q | grep Caps | awk '{ print $4 }')

if [ "$caps_status" = "on" ]; then
  echo "  <span font_size='x-large'></span>  "
  exit 33
else
  echo "<span color='#aaa'> <b>·</b> </span>"
fi
