#!/bin/sh
#
# Saumon i3blocks scripts
# desktopbrightness (display and change external monitor brightness)
#

command="ddcutil --bus $BLOCK_INSTANCE"

case $BLOCK_BUTTON in
  2) # middle click: toggle night/day brightness
    current=$($command getvcp 10 --brief | awk '{print $4}')
    if [ "$current" -le 20 ]; then
      if [ "$BLOCK_INSTANCE" -eq 6 ]; then
        new=100
      else
        new=60
      fi
    else
      if [ "$BLOCK_INSTANCE" -eq 6 ]; then
        new=20
      else
        new=0
      fi
    fi
    ;;
  3) # right click: set min/full brightness depending on context
    current=$($command getvcp 10 --brief | awk '{print $4}')
    if [ "$current" -ge 50 ]; then
      new=100
    else
      new=0
    fi
    ;;
  4) # scroll up: increase brightness by 20%
    current=$($command getvcp 10 --brief | awk '{print $4}')
    if [ "$current" -ge 80 ]; then
      new=100
    else
      new=$(expr $current + 20)
    fi
    ;;
  5) # scroll down: decrease brightness by 20%
    current=$($command getvcp 10 --brief | awk '{print $4}')
    if [ "$current" -le 20 ]; then
      new=0
    else
      new=$(expr $current - 20)
    fi
    ;;
esac

if [ -n "$new" ]; then
  printf " <span fallback='true'>  </span>%s<span font_size='small'>%%</span> \n" "$new"
  $command setvcp 10 $new --noverify &
  exit 0
fi

current=$($command getvcp 10 --brief | awk '{print $4}')

if [ -z "$current" ]; then
  printf " <span fallback='true'>  </span>?? \n"
  exit 0
fi

printf " <span fallback='true'>  </span>%s<span font_size='small'>%%</span> \n" "$current"
