#!/bin/sh
#
# Saumon i3blocks scripts
# INTERNET (wired/wifi network info with external ip on middle click)
#

ifaceWIFI=$(echo /sys/class/net/*/wireless | awk -F '/' '{ print $5 }')
ifaceETH=$(echo /sys/class/net/en*/ | awk '{ print $NF }' | awk -F '/' '{ print $5 }')
VPNStatus=$(nmcli -g type,uuid -c no connection show --active | grep "vpn:" | cut -d ':' -f 2 | xargs nmcli -f STATE con show | awk '{ print $2 }')

case $BLOCK_BUTTON in
  2)
    IP=$(curl -s "https://ip.saumon.io" | tr -d '\n')
    IP4=$(curl -s "https://ip4.saumon.io" | tr -d '\n')
    IP6=$(curl -s "https://ip6.saumon.io" | tr -d '\n')
    if [ "$IP" = "$IP6" ]; then
      message="$IP\n<u>IPv4</u>: $IP4 <i>(copied)</i>"
    elif [ "$IP" = "$IP4" ]; then
      message="$IP <i>(copied)</i>\n<u>IPv6</u>: $IP6"
    else
      message="$IP\n<u>IPv4</u>: $IP4 <i>(copied)</i>\n<u>IPv6</u>: $IP6"
    fi
    notify-send "External IP address" "$message"
    echo -n "$IP4" | xclip -i -selection clipboard 1>/dev/null 2>&1
    ;;
  3)
    IP=$(ip addr show | awk '/inet / {print $2}' | grep -v "127.0.0.1" | cut -d '/' -f1 | tr -d '\n')
    notify-send "IP address" "$IP (copied)"
    echo -n "$IP" | xclip -i -selection clipboard 1>/dev/null 2>&1
    ;;
esac

if [ -n "$ifaceWIFI" ] && [ "$ifaceWIFI" != "*" ]; then
  statusWIFI=$(cat -- "$(readlink -e -- /sys/class/net/"$ifaceWIFI"/operstate)")
else
  statusWIFI="unknown"
fi

if [ -n "$ifaceETH" ] && [ "$ifaceETH" != "en*" ]; then
  statusETH=$(cat -- "$(readlink -e -- /sys/class/net/"$ifaceETH"/operstate)")
else
  statusETH="unknown"
fi

if [ "$statusETH" = "up" ]; then
  printf '<span color="#8BC34A">   '
  ip addr show "$ifaceETH" | awk '/inet / {print $2}' | cut -d '/' -f1 | tr -d '\n'
  printf '</span>'
  if [ "$VPNStatus" = "activated" ]; then
    printf " <span color='#EC407A'> </span>"
  elif [ "$VPNStatus" = "activating" ]; then
    printf " <span color='#777777'> </span>"
  fi
  printf ' \n'
elif [ "$statusWIFI" = "up" ]; then
  IPaddr=$(ip addr show "$ifaceWIFI" | awk '/inet / {print $2}' | cut -d '/' -f1 | tr -d '\n')
  NetName=$(iwgetid -r | tr -d '\n')
  SignalStrength=$(awk 'NR==3 {print substr($3, 1, 2)}' /proc/net/wireless)
  if [ "$IPaddr" = "" ]; then
    printf "<span color='#EF6C00'>   (no IP)</span>\n"
  else
    if [ "$SignalStrength" -ge 50 ]; then
      signalcolor='#8BC34A'
    elif [ "$SignalStrength" -ge 30 ]; then
      signalcolor='#EF6C00'
    else
      signalcolor='#f44336'
    fi
    printf "<span color='$signalcolor'> </span><span font_size='small'> </span> <span color='#8BC34A'>"
    case "$IPaddr" in
      192.168.*) printf "%s" "${IPaddr#'192.168.'}" ;;
      10.0.*) printf "<span font_size='small'>10.0.</span>%s" "${IPaddr#'10.0.'}" ;;
      10.1.*) printf "<span font_size='small'>10.1.</span>%s" "${IPaddr#'10.1.'}" ;;
      10.41.*) printf "<span font_size='small'>10.41.</span>%s" "${IPaddr#'10.41.'}" ;;
      *) printf "%s" "$IPaddr" ;;
    esac
    printf "</span> <span font_size='small' color='#cccccc'>on</span> "
    case "$NetName" in  # yeah what a shitty way to know if the network is 5GHz, right?
      *-5GHz) printf "%s <span color='#1E88E5' font_weight='bold'>5</span>" "${NetName%?????}" ;;
      *-5G) printf "%s <span color='#1E88E5' font_weight='bold'>5</span>" "${NetName%???}" ;;
      *) printf "%s" "$NetName" ;;
    esac
    if [ "$VPNStatus" = "activated" ]; then
      printf " <span color='#EC407A'> </span>"
    elif [ "$VPNStatus" = "activating" ]; then
      printf " <span color='#777777'> </span>"
    fi
    printf " \n"
  fi
else
  printf "<span color='#f44336'> internet c'est cassé </span>\n"
fi
