#!/bin/sh
#
# Saumon i3blocks scripts : load
# (1 minute load with colors)
#

nproc=$(nproc)
warningPercent=$(echo "$nproc * 60" | bc -l | tr -d '\n')
criticalPercent=$(echo "$nproc * 80" | bc -l | tr -d '\n')

load=$(cut -d ' ' -f1 /proc/loadavg | tr -d '\n')
loadPercent=$(echo "$load * 100" | bc -l | xargs printf "%.0f")

if [ "$loadPercent" -ge "$criticalPercent" ]; then
  color="#f44336"
elif [ "$loadPercent" -ge "$warningPercent" ]; then
  color="#ff9800"
else
  color="#cccccc"
fi

printf "<span color='%s'>   %s</span> \n" "$color" "$load"
