#!/usr/bin/env bash
#
# Saumon i3blocks scripts
# load (1 minute load with colors)
#

nproc=$(nproc)
warningPercent=$(( nproc * 60 ))
criticalPercent=$(( nproc * 90 ))

load=$(cut -d ' ' -f1 /proc/loadavg)
loadPercent=$(echo "$load * 100" | bc -l | xargs printf "%.0f")

if [ "$loadPercent" -ge "$criticalPercent" ]; then
  color="#f44336"
elif [ "$loadPercent" -ge "$warningPercent" ]; then
  color="#ff9800"
else
  color="#cccccc"
fi

printf "<span color='%s'>   %s</span> \n" "$color" "$load"
