#!/usr/bin/env sh
#
# Saumon i3blocks scripts
# temperature (hardware temperature)
#

if ! command -v sensors >/dev/null; then
  echo " !dep "
  exit 33
fi

temp=$(sensors "$BLOCK_INSTANCE" | grep Tctl | awk '{print substr($2,2);}' | cut -d '.' -f1)

if [ "$temp" -ge 80 ]; then
  color="#f44336"
  icon=""
elif [ "$temp" -ge 60 ]; then
  color="#ff9800"
  icon=""
elif [ "$temp" -ge 50 ]; then
  color="#dddddd"
  icon=""
else
  color="#dddddd"
  icon=""
fi

printf "<span color='%s'> %s  %s<span font_size='small'>°C</span></span>\n" "$color" "$icon" "$temp"
