#!/bin/bash
#
# Saumon i3blocks scripts
# volume (display main volume, mute on right click and change on scroll)
#

case $BLOCK_BUTTON in
  2) pgrep pavucontrol || pavucontrol & ;; # middle click: bring up volume mixer
  3) pactl set-sink-mute @DEFAULT_SINK@ toggle ;; # right click: toggle mute
  4) pactl set-sink-volume @DEFAULT_SINK@ +4% ;; # scroll up: increase vol by 4%
  5) pactl set-sink-volume @DEFAULT_SINK@ -4% ;; # scroll down: decrease vol by 4%
esac

active_sink=$(pactl get-default-sink)
sink=$(pactl list sinks | grep -A100 "Name: $active_sink")
if [[ "$sink" == *"bluez"* ]]; then isbluetooth=1; fi
if [[ "$sink" == *"Active Port: analog-output-headphone"* ]]; then isheadphone=1; fi
# I can we can use `pactl get-sink-mute @DEFAULT_SINK@` but it's less efficient :)
if [[ "$sink" == *"Mute: yes"* ]]; then ismuted=1; fi
volume=$(echo "$sink" | grep "Volume: front" | awk '{print $5}' | tr -d '%')

if [ -n "$isbluetooth" ]; then
  if [ -n "$ismuted" ]; then
    color="#997CC5"
  else
    color="#1E88E5"
  fi
elif [ -n "$isheadphone" ]; then
  if [ -n "$ismuted" ]; then
    color="#FBC02D"
  else
    color="#F8E744"
  fi
elif [ -n "$ismuted" ]; then
  color="#EF6C00"
else
  color="#dddddd"
fi

printf "<span color='%s'>" "$color"

if [ -n "$ismuted" ]; then
  printf "<s> "
fi
if [ -n "$isbluetooth" ]; then
  printf "<span fallback='true'>  </span>"
fi
if [ "$volume" -ge 40 ]; then
  printf "<span fallback='true'>  </span>%s" "$volume"
else
  printf "<span fallback='true'>  </span>%s" "$volume"
fi

printf "<small>%%</small>"

if [ -n "$ismuted" ]; then
  printf " </s>"
fi

echo "</span>"
