#!/bin/sh
#
# Saumon i3blocks scripts
# volume (display main volume, mute on right click and change on scroll)
#

case $BLOCK_BUTTON in
  3) pactl set-sink-mute @DEFAULT_SINK@ toggle ;; # right click : toggle mute
  4) pactl set-sink-volume @DEFAULT_SINK@ +4% ;; # scroll up : increase vol by 4%
  5) pactl set-sink-volume @DEFAULT_SINK@ -4% ;; # scroll down : decrease vol by 4%
esac

active_sink=$(pactl info | sed -En 's/Default Sink: (.*)/\1/p')
sink=$(pactl list sinks | grep -A100 "Name: $active_sink")
isbluetooth=$(echo "$sink" | grep bluez)
isheadphone=$(echo "$sink" | grep "Active Port: analog-output-headphone")
ismuted=$(echo "$sink" | grep "Mute: " | awk '{print $2}')
volume=$(echo "$sink" | grep "Volume: " | head -1 | awk '{print $5}' | tr -d '%')

if [ -n "$isbluetooth" ]; then
  color="#1E88E5"
  if [ "$ismuted" = "yes" ]; then
    color="#997CC5"
  fi
elif [ -n "$isheadphone" ]; then
  color="#F8E744"
  if [ "$ismuted" = "yes" ]; then
    color="#FBC02D"
  fi
elif [ "$ismuted" = "yes" ]; then
  color="#EF6C00"
else
  color="#dddddd"
fi

printf "<span color='%s'>" "$color"

if [ "$ismuted" = "yes" ]; then
  printf "<s> "
fi
if [ -n "$isbluetooth" ]; then
  printf "<span fallback='true'>  </span>"
fi
if [ "$volume" -ge 40 ]; then
  printf "<span fallback='true'>  </span>%s" "$volume"
else
  printf "<span fallback='true'>  </span>%s" "$volume"
fi

printf "<small>%%</small>"

if [ "$ismuted" = "yes" ]; then
  printf " </s>"
fi

echo "</span>"
